### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by JesperHarders** [rts-cmk-wu06/smartlight-ui-JesperHarders#6]
- [ ] Animation when tapping on a room card
- [x] Animation for buttons sliding in from the right (Issue #2 Task 6)
- [x] Animation for buttons sliding in from the left (Issue #3 Task 3 and 4)
- [x] Animation for number of lights dropping down from above (Issue #2 Task 4)
- [ ] Animation for bubbles
